package com.xaicomply.common.dto;

import com.xaicomply.common.enums.ComplianceStatus;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.Instant;
import java.util.List;
import java.util.Map;

/**
 * Compliance report aggregating multiple transaction mapping results.
 * Generated by the Reporting Service (Spring Batch job).
 *
 * Maps to the "audit-ready report" described in the paper (Section 2.3).
 * Stored in H2 (local) or S3 (production).
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ComplianceReportDTO {

    /** Unique report identifier */
    private String reportId;

    /** Report generation timestamp */
    @Builder.Default
    private Instant generatedAt = Instant.now();

    /** Time window covered by this report */
    private Instant periodStart;
    private Instant periodEnd;

    // ── Aggregate statistics ─────────────────────────────────────────────────

    private Integer totalTransactions;
    private Integer flaggedTransactions;
    private Integer violationCount;
    private Integer reviewCount;
    private Integer compliantCount;

    /** Flagged rate = flaggedTransactions / totalTransactions */
    private Double flaggedRate;

    /** Average regulatory risk score across all transactions */
    private Double averageRiskScore;

    /** Maximum regulatory risk score in this period */
    private Double maxRiskScore;

    /** Breakdown by compliance status */
    private Map<ComplianceStatus, Integer> statusBreakdown;

    /** Top 5 most-flagged features across all transactions */
    private List<String> topRiskFeatures;

    // ── Individual records ────────────────────────────────────────────────────

    /** Full list of mapping results included in this report */
    private List<MappingResultDTO> records;

    // ── Batch job metadata ────────────────────────────────────────────────────

    /** Spring Batch job execution ID */
    private Long batchJobId;

    /** Report generation time in ms (latency KPI from paper) */
    private Long generationTimeMs;

    /** File path where report was saved */
    private String reportFilePath;
}
