package com.xaicomply.common.dto;

import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.PositiveOrZero;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.UUID;

/**
 * Raw transaction input DTO.
 *
 * Schema matches the Kaggle Credit Card Fraud Detection dataset:
 *   https://www.kaggle.com/datasets/mlg-ulb/creditcardfraud
 *
 * Features:
 *   - time:   seconds elapsed since the first transaction in the dataset
 *   - v1-v28: PCA-transformed features (anonymized for privacy)
 *   - amount: transaction amount in EUR
 *
 * The 'transactionId' field is generated by the client or assigned during ingestion.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class TransactionDTO {

    /** Unique identifier for this transaction. Generated if not provided. */
    @Builder.Default
    private String transactionId = UUID.randomUUID().toString();

    /** Seconds elapsed since dataset reference point. Used for velocity checks. */
    @NotNull(message = "Time field is required")
    @PositiveOrZero(message = "Time must be >= 0")
    private Double time;

    // ── PCA-transformed features V1–V28 ──────────────────────────────────────
    // These are the result of PCA on the original (confidential) features.
    // They map to φ₁…φ₂₈ in the SHAP attribution vector.

    @NotNull private Double v1;
    @NotNull private Double v2;
    @NotNull private Double v3;
    @NotNull private Double v4;
    @NotNull private Double v5;
    @NotNull private Double v6;
    @NotNull private Double v7;
    @NotNull private Double v8;
    @NotNull private Double v9;
    @NotNull private Double v10;
    @NotNull private Double v11;
    @NotNull private Double v12;
    @NotNull private Double v13;
    @NotNull private Double v14;
    @NotNull private Double v15;
    @NotNull private Double v16;
    @NotNull private Double v17;
    @NotNull private Double v18;
    @NotNull private Double v19;
    @NotNull private Double v20;
    @NotNull private Double v21;
    @NotNull private Double v22;
    @NotNull private Double v23;
    @NotNull private Double v24;
    @NotNull private Double v25;
    @NotNull private Double v26;
    @NotNull private Double v27;
    @NotNull private Double v28;

    /** Transaction amount in EUR. High AML/KYC relevance → high regulatory weight ω. */
    @NotNull(message = "Amount is required")
    @PositiveOrZero(message = "Amount must be >= 0")
    private Double amount;

    /**
     * Optional: true label for simulation/testing against ground truth.
     * 0 = legitimate, 1 = fraud.
     * NOT used by the ML model — only for evaluation metrics.
     */
    @JsonProperty("true_label")
    private Integer trueLabel;

    /**
     * Convert this DTO's features into a float array for ONNX model input.
     * Order MUST match the training feature order in train_model.py:
     *   [Time, V1, V2, ..., V28, Amount]
     * Total = 30 features.
     */
    public float[] toFeatureArray() {
        return new float[]{
                time.floatValue(),
                v1.floatValue(), v2.floatValue(), v3.floatValue(), v4.floatValue(),
                v5.floatValue(), v6.floatValue(), v7.floatValue(), v8.floatValue(),
                v9.floatValue(), v10.floatValue(), v11.floatValue(), v12.floatValue(),
                v13.floatValue(), v14.floatValue(), v15.floatValue(), v16.floatValue(),
                v17.floatValue(), v18.floatValue(), v19.floatValue(), v20.floatValue(),
                v21.floatValue(), v22.floatValue(), v23.floatValue(), v24.floatValue(),
                v25.floatValue(), v26.floatValue(), v27.floatValue(), v28.floatValue(),
                amount.floatValue()
        };
    }

    /** Feature names in the same order as toFeatureArray(). */
    public static String[] featureNames() {
        return new String[]{
                "Time",
                "V1","V2","V3","V4","V5","V6","V7","V8","V9","V10",
                "V11","V12","V13","V14","V15","V16","V17","V18","V19","V20",
                "V21","V22","V23","V24","V25","V26","V27","V28",
                "Amount"
        };
    }
}
